services:
  - type: web
    name: vdb-map-bangladesh
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000
